Weather Station: Menu Public Functions
Menu Public Functions
Menu
Functions
void * init_menu ()
initialize menu
void * up_and_down_pressed (void *origen(), void *destiny(), void(*led_state)())
manage the up and down button function time. If up and down button are pressed
Detailed Description
Function Documentation
init_menu()
void* init_menu ()
initialize menu
Note
must be called first
Definition at line 16 of file menu.c.
References init_data_st(), and normal_execution().
Referenced by main().
up_and_down_pressed()
void* up_and_down_pressed (void * origen(), void * destiny(), void(*)() led_state)
manage the up and down button function time. If up and down button are pressed
Definition at line 23 of file menu.c.
References button_map, count, PRESSING_TIME, RELEASE_TIME, and TWO_SECONDS.
Referenced by maintenance_execution(), and normal_execution().