Weather Station: View Public Functions
View Public Functions
View
Functions
void view_normal ()
void view_maintenance (short idx)
void view_change_time ()
void view_change_date ()
void view_change_temperature_units ()
Detailed Description
Function Documentation
view_change_date()
void view_change_date ()
@ change date view
Definition at line 37 of file view.c.
References get_Date(), str, and view_maintenance().
view_change_temperature_units()
void view_change_temperature_units ()
@ change temperature view
Definition at line 42 of file view.c.
References get_Temperature(), str, and view_maintenance().
view_change_time()
void view_change_time ()
@ change time view
Definition at line 32 of file view.c.
References get_Time(), str, and view_maintenance().
view_maintenance()
void view_maintenance (short idx)
@ maintenance mode view
Definition at line 25 of file view.c.
References MAINTENANCE_CHANGE_TITLE, and str.
Referenced by view_change_date(), view_change_temperature_units(), and view_change_time().
view_normal()
void view_normal ()
@ normal mode view
Definition at line 16 of file view.c.
References dateTimeToString(), str, and TemperatureAndPressureToString().
Referenced by normal_execution().