Weather Station: Date Storage Static Constants
Date Storage Static Constants
Data Storage
const char SEC_CHARACTER [2] ={' ',':'}
arry that represents the current second. ' ' even second, ':' odd second
const char TEMPERATURE_UNIT [2] ={'C','F'}
arry that represents the temperature units
int * TIME_PTRS [TIME_FIELDS] ={&(dateTime.tm_hour),&(dateTime.tm_min)}
arry that represents the pointers of time in time structure
const int MAX_TIMES [TIME_FIELDS] ={MAX_HOUR, MAX_MIN}
arry that represents the maximum values of hour and minutes
int * DATE_PTRS [DATE_FIELDS] ={&(dateTime.tm_year),&(dateTime.tm_mon),&(dateTime.tm_mday)}
arry that represents the pointers of date in time structure
int MAX_DATES [DATE_FIELDS] ={MAX_YEAR, MAX_MONTH, MAX_DAY}
arry that represents the maximum values of years, months and days
int DATE_OFFSETS [DATE_FIELDS] ={YEAR_OFFSET, MONTH_OFFSET, DAY_OFFSET}
arry that represents the offset values of years, months and days
double(* temperatureUnit [2])() ={&celsius,&celsius_to_fahrenheit}
array of function pointers to return the current temperature in UNIT index
Detailed Description
Variable Documentation
DATE_OFFSETS
int DATE_OFFSETS[DATE_FIELDS] ={YEAR_OFFSET, MONTH_OFFSET, DAY_OFFSET}
arry that represents the offset values of years, months and days
Definition at line 66 of file data_storage.c.
Referenced by change_date().
DATE_PTRS
int* DATE_PTRS[DATE_FIELDS] ={&(dateTime.tm_year),&(dateTime.tm_mon),&(dateTime.tm_mday)}
arry that represents the pointers of date in time structure
Definition at line 56 of file data_storage.c.
Referenced by change_date().
MAX_DATES
int MAX_DATES[DATE_FIELDS] ={MAX_YEAR, MAX_MONTH, MAX_DAY}
arry that represents the maximum values of years, months and days
Definition at line 61 of file data_storage.c.
Referenced by change_date().
MAX_TIMES
const int MAX_TIMES[TIME_FIELDS] ={MAX_HOUR, MAX_MIN}
arry that represents the maximum values of hour and minutes
Definition at line 51 of file data_storage.c.
Referenced by change_time().
SEC_CHARACTER
const char SEC_CHARACTER[2] ={' ',':'}
arry that represents the current second. ' ' even second, ':' odd second
Definition at line 36 of file data_storage.c.
Referenced by dateTimeToString().
TEMPERATURE_UNIT
const char TEMPERATURE_UNIT[2] ={'C','F'}
arry that represents the temperature units
Definition at line 41 of file data_storage.c.
Referenced by get_Temperature(), and TemperatureAndPressureToString().
temperatureUnit
double(* temperatureUnit[2])() ={&celsius,&celsius_to_fahrenheit}
array of function pointers to return the current temperature in UNIT index
Definition at line 71 of file data_storage.c.
Referenced by get_Temperature(), and TemperatureAndPressureToString().
TIME_PTRS
int* TIME_PTRS[TIME_FIELDS] ={&(dateTime.tm_hour),&(dateTime.tm_min)}
arry that represents the pointers of time in time structure
Definition at line 46 of file data_storage.c.
Referenced by change_time().