Weather Station: Data Storage Public Functions
Data Storage Public Functions
Data Storage
Functions
void init_data_st ()
Initialize data storage functions.
void backup_dateTime ()
saves the current date time at dateTime pointer
void send_time ()
calls send_dateTime with timer mask
void send_date ()
calls send_dateTime with date mask
void send_temp_unit ()
send the Temperature Unit
void send_dateTime (short mask)
send the updated time/date to RTC
void dateTimeToString (char *str)
transform the current date into a string
void TemperatureAndPressureToString (char *str)
transform the current temperature and pressure into a string
void get_Time (char *str)
writes in str the current time
void get_Temperature (char *str)
writes in str the current temperature
void get_Date (char *str)
writes in str the current date
void change_time (int val)
add to the current time the val
void change_date (int val)
add to the current date the val
void change_temp_unit (int val)
change the temperature unit
int nextField (int type)
advance to the next field. In Time it goes from HH to mm. In Date it goes from YYYY to MM and then to DD
int get_CurrentField ()
Detailed Description
Function Documentation
backup_dateTime()
void backup_dateTime ()
saves the current date time at dateTime pointer
Definition at line 106 of file data_storage.c.
References dateTime, and fieldToChange.
Referenced by select_field().
change_date()
void change_date (int val)
add to the current date the val
Definition at line 155 of file data_storage.c.
References DATE_OFFSETS, DATE_PTRS, dateTime, FEBRUARY, fieldToChange, MAX_DATES, and MAX_DAYS_MAP.
Referenced by date_up_down_pressed().
change_temp_unit()
void change_temp_unit (int val)
change the temperature unit
Definition at line 167 of file data_storage.c.
References aux, and FAHRENHEIT.
Referenced by temp_up_down_pressed().
change_time()
void change_time (int val)
add to the current time the val
Definition at line 149 of file data_storage.c.
References fieldToChange, MAX_TIMES, and TIME_PTRS.
Referenced by time_up_down_pressed().
dateTimeToString()
void dateTimeToString (char * str)
transform the current date into a string
Definition at line 130 of file data_storage.c.
References dateTime, SEC_CHARACTER, and str.
Referenced by view_normal().
get_CurrentField()
int get_CurrentField ()
Returns
returns the current field
Definition at line 178 of file data_storage.c.
References fieldToChange.
Referenced by maintenance_change_date(), and maintenance_change_time().
get_Date()
void get_Date (char * str)
writes in str the current date
Definition at line 145 of file data_storage.c.
References dateTime, and str.
Referenced by view_change_date().
get_Temperature()
void get_Temperature (char * str)
writes in str the current temperature
Definition at line 190 of file data_storage.c.
References aux, str, TEMPERATURE_UNIT, and temperatureUnit.
Referenced by view_change_temperature_units().
get_Time()
void get_Time (char * str)
writes in str the current time
Definition at line 141 of file data_storage.c.
References dateTime, and str.
Referenced by view_change_time().
init_data_st()
void init_data_st ()
Initialize data storage functions.
Note
must be called first
Definition at line 97 of file data_storage.c.
References aux, CELSIUS, dateTime, FAHRENHEIT, fieldToChange, and unit.
Referenced by init_menu().
nextField()
int nextField (int type)
advance to the next field. In Time it goes from HH to mm. In Date it goes from YYYY to MM and then to DD
Definition at line 174 of file data_storage.c.
References fieldToChange.
Referenced by date_enter_pressed(), and time_enter_pressed().
send_date()
void send_date ()
calls send_dateTime with date mask
Definition at line 115 of file data_storage.c.
References send_dateTime().
Referenced by date_enter_pressed().
send_dateTime()
void send_dateTime (short mask)
send the updated time/date to RTC
Definition at line 125 of file data_storage.c.
References dateTime, and fieldToChange.
Referenced by send_date(), and send_time().
send_temp_unit()
void send_temp_unit ()
send the Temperature Unit
Definition at line 119 of file data_storage.c.
References aux, fieldToChange, and unit.
Referenced by temp_enter_pressed().
send_time()
void send_time ()
calls send_dateTime with timer mask
Definition at line 111 of file data_storage.c.
References send_dateTime().
Referenced by time_enter_pressed().
TemperatureAndPressureToString()
void TemperatureAndPressureToString (char * str)
transform the current temperature and pressure into a string
Definition at line 135 of file data_storage.c.
References aux, str, TEMPERATURE_UNIT, temperatureUnit, and unit.
Referenced by view_normal().