Weather Station: Menu Normal Public Constants
Menu Normal Public Constants
Menu Normal
Functions
void * normal_execution ()
Detailed Description
Function Documentation
normal_execution()
void* normal_execution ()
Returns
return a pointer to a normal menu function
Definition at line 12 of file menu_normal.c.
References button_map, count, maintenance_execution(), up_and_down_pressed(), and view_normal().
Referenced by init_menu(), and maintenance_execution().