Weather Station: Menu Maintenance Static Functions
Menu Maintenance Static Functions
Menu Maintenance
static void maintenance_buttons_interaction ()
read the current button state and executes an action
static void select_up_pressed (short value)
executes an action after only the up button is pressed while in select mode
static void select_down_pressed (short value)
executes an action after only the down button is pressed while in select mode
static void select_enter_pressed ()
executes an action after only the enter button is pressed while in select mode
static void time_up_down_pressed (short value)
executes an action after the up xor down button are pressed while in maintenance mode and time was selected
static void time_enter_pressed ()
executes an action after the enter button is pressed while in in maintenance mode and time was selected
static void date_up_down_pressed (short value)
executes an action after the up xor down button is pressed while in in maintenance mode and date was selected
static void date_enter_pressed ()
executes an action after the enter button is pressed while in in maintenance mode and date was selected
static void temp_up_down_pressed (short value)
executes an action after the up xor down button is pressed while in in maintenance mode and temperature unit was selected
static void temp_enter_pressed ()
executes an action after the enter button is pressed while in in maintenance mode and temperature unit was selected
static void select_field ()
executes the select mode
static void maintenance_change_time ()
executes the maintenance mode to change time
static void maintenance_change_date ()
executes the maintenance mode to change date
static void maintenance_change_temperature_units ()
executes the maintenance mode to change temperature unit
Detailed Description
Function Documentation
date_enter_pressed()
void date_enter_pressed () static
executes an action after the enter button is pressed while in in maintenance mode and date was selected
Definition at line 250 of file menu_maintenance.c.
References button_map, DATE_FIELDS, mode_idx, nextField(), send_date(), view, and view_idx.
date_up_down_pressed()
void date_up_down_pressed (short value) static
executes an action after the up xor down button is pressed while in in maintenance mode and date was selected
Definition at line 240 of file menu_maintenance.c.
References change_date(), count_continuos_pressing, count_pressing_button, ONE_SECOND, view, and view_idx.
maintenance_buttons_interaction()
void maintenance_buttons_interaction () static
read the current button state and executes an action
Definition at line 169 of file menu_maintenance.c.
References button_map, count_continuos_pressing, enter_funcs, mode_idx, up_down_func, and view_idx.
Referenced by maintenance_change_date(), maintenance_change_temperature_units(), maintenance_change_time(), and select_field().
maintenance_change_date()
void maintenance_change_date () static
executes the maintenance mode to change date
Definition at line 287 of file menu_maintenance.c.
References get_CurrentField(), and maintenance_buttons_interaction().
maintenance_change_temperature_units()
void maintenance_change_temperature_units () static
executes the maintenance mode to change temperature unit
Definition at line 293 of file menu_maintenance.c.
References maintenance_buttons_interaction().
maintenance_change_time()
void maintenance_change_time () static
executes the maintenance mode to change time
Definition at line 281 of file menu_maintenance.c.
References get_CurrentField(), and maintenance_buttons_interaction().
select_down_pressed()
void select_down_pressed (short value) static
executes an action after only the down button is pressed while in select mode
Definition at line 197 of file menu_maintenance.c.
References button_map, and view_idx.
select_enter_pressed()
void select_enter_pressed () static
executes an action after only the enter button is pressed while in select mode
Definition at line 205 of file menu_maintenance.c.
References button_map, mode_idx, and view_idx.
select_field()
void select_field () static
executes the select mode
Definition at line 212 of file menu_maintenance.c.
References backup_dateTime(), maintenance_buttons_interaction(), view, and view_idx.
select_up_pressed()
void select_up_pressed (short value) static
executes an action after only the up button is pressed while in select mode
Definition at line 190 of file menu_maintenance.c.
References button_map, and view_idx.
temp_enter_pressed()
void temp_enter_pressed () static
executes an action after the enter button is pressed while in in maintenance mode and temperature unit was selected
Definition at line 272 of file menu_maintenance.c.
References button_map, mode_idx, and send_temp_unit().
temp_up_down_pressed()
void temp_up_down_pressed (short value) static
executes an action after the up xor down button is pressed while in in maintenance mode and temperature unit was selected
Definition at line 262 of file menu_maintenance.c.
References change_temp_unit(), count_pressing_button, view, and view_idx.
time_enter_pressed()
void time_enter_pressed () static
executes an action after the enter button is pressed while in in maintenance mode and time was selected
Definition at line 228 of file menu_maintenance.c.
References button_map, mode_idx, nextField(), send_time(), TIME_FIELDS, view, and view_idx.
time_up_down_pressed()
void time_up_down_pressed (short value) static
executes an action after the up xor down button are pressed while in maintenance mode and time was selected
Definition at line 218 of file menu_maintenance.c.
References change_time(), count_continuos_pressing, count_pressing_button, ONE_SECOND, view, and view_idx.