Weather Station: D:/Isel/19-20/Inverno/SE1/project/src/menu_maintenance.c File Reference
menu_maintenance.c File Reference
Contains the Menu Maintenance source.
#include "menu_maintenance.h"
Functions
void * maintenance_execution ()
static void maintenance_buttons_interaction ()
read the current button state and executes an action
static void select_up_pressed (short value)
executes an action after only the up button is pressed while in select mode
static void select_down_pressed (short value)
executes an action after only the down button is pressed while in select mode
static void select_enter_pressed ()
executes an action after only the enter button is pressed while in select mode
static void time_up_down_pressed (short value)
executes an action after the up xor down button are pressed while in maintenance mode and time was selected
static void time_enter_pressed ()
executes an action after the enter button is pressed while in in maintenance mode and time was selected
static void date_up_down_pressed (short value)
executes an action after the up xor down button is pressed while in in maintenance mode and date was selected
static void date_enter_pressed ()
executes an action after the enter button is pressed while in in maintenance mode and date was selected
static void temp_up_down_pressed (short value)
executes an action after the up xor down button is pressed while in in maintenance mode and temperature unit was selected
static void temp_enter_pressed ()
executes an action after the enter button is pressed while in in maintenance mode and temperature unit was selected
static void select_field ()
executes the select mode
static void maintenance_change_time ()
executes the maintenance mode to change time
static void maintenance_change_date ()
executes the maintenance mode to change date
static void maintenance_change_temperature_units ()
executes the maintenance mode to change temperature unit
Variables
void(* view [3])() ={view_change_time, view_change_date, view_change_temperature_units}
array of function pointers to select which view was selected
void(* mode [4])() ={select_field, maintenance_change_time, maintenance_change_date, maintenance_change_temperature_units}
array of function pointers to select which mode is to be called to execute maintenance
void(* enter_funcs [])() ={select_enter_pressed, time_enter_pressed, date_enter_pressed, temp_enter_pressed}
array of function pointers to be called when enter button is pressed in the current mode
void(* up_down_func [])(short value) ={select_up_pressed, select_down_pressed, time_up_down_pressed, date_up_down_pressed, temp_up_down_pressed}
array of function pointers to be called when up xor button button is pressed in the current mode
uint32_t count_10
keep track of time passed up to 10 seconds if no button is pressed
uint32_t count_pressing_button
count how long is the button pressed to delay the execution of the command
uint32_t count_continuos_pressing
count how long is the button pressed to increased the incremented value of the fields
short view_idx =0
the current view index
short mode_idx =0
the current mode index
Detailed Description
Contains the Menu Maintenance source.
Version
1.1
Date
4 Out 2017
Author
Ricardo Romano, André Dias, Manuel Dias @numbers 43924, 40619, 38866
Definition in file menu_maintenance.c.
Variable Documentation
enter_funcs
void(* enter_funcs[])() ={select_enter_pressed, time_enter_pressed, date_enter_pressed, temp_enter_pressed}
array of function pointers to be called when enter button is pressed in the current mode
Definition at line 100 of file menu_maintenance.c.
Referenced by maintenance_buttons_interaction().
mode
void(* mode[4])() ={select_field, maintenance_change_time, maintenance_change_date, maintenance_change_temperature_units}
array of function pointers to select which mode is to be called to execute maintenance
Definition at line 95 of file menu_maintenance.c.
Referenced by maintenance_execution().
up_down_func
void(* up_down_func[])(short value) ={select_up_pressed, select_down_pressed, time_up_down_pressed, date_up_down_pressed, temp_up_down_pressed}
array of function pointers to be called when up xor button button is pressed in the current mode
Definition at line 105 of file menu_maintenance.c.
Referenced by maintenance_buttons_interaction().
view
void(* view[3])() ={view_change_time, view_change_date, view_change_temperature_units}
array of function pointers to select which view was selected
Definition at line 90 of file menu_maintenance.c.
Referenced by date_enter_pressed(), date_up_down_pressed(), select_field(), temp_up_down_pressed(), time_enter_pressed(), and time_up_down_pressed().