Embedded Systems Library: Button Public Functions
Button Public Functions
Button
Functions
void init_BUTTON (void)
Initializes the Button API.
int BUTTON_Hit (void)
Read the buttons values.
int BUTTON_Read (void)
Call the Button_init function, just one. Check if some button is pressed.
int BUTTON_GetButtonsEvents (void)
Check if there is any change at the buttons state.
Detailed Description
Function Documentation
BUTTON_GetButtonsEvents()
int BUTTON_GetButtonsEvents (void)
Check if there is any change at the buttons state.
Returns
Bitmap code. 0:1-> up button state, 2:3 -> down button state, 4:5 -> enter button state
Definition at line 47 of file button.c.
References BUTTON_check(), BUTTON_Hit(), buttons_state, BUTTONS_STATE_TYPEDEF::down, DOWN_BUTTON_MASK, BUTTONS_STATE_TYPEDEF::enter, ENTER_BUTTON_MASK, BUTTONS_STATE_TYPEDEF::up, and UP_BUTTON_MASK.
BUTTON_Hit()
int BUTTON_Hit (void)
Read the buttons values.
Returns
bitmap code 0 if there is no button pressed.
Definition at line 18 of file button.c.
References BUTTONS_MASK.
Referenced by BUTTON_GetButtonsEvents(), and BUTTON_Read().
BUTTON_Read()
int BUTTON_Read (void)
Call the Button_init function, just one. Check if some button is pressed.
Returns
bitmap code.
Definition at line 24 of file button.c.
References BUTTON_Hit().
init_BUTTON()
void init_BUTTON (void)
Initializes the Button API.
Note
This function must be called prior to any other BUTTON functions.
Definition at line 12 of file button.c.
References DOWN_BUTTON_PIN, ENTER_BUTTON_PIN, PINCFG_DOWN_BUTTON, PINCFG_ENTER_BUTTON, PINCFG_PULLUP, PINCFG_UP_BUTTON, and UP_BUTTON_PIN.
Referenced by init_ui().