Embedded Systems Library: Wait Public Functions
Wait Public Functions
Wait
Functions
void init_wait ()
Initialises the wait API for 1 ms resolution.
void wait_hz (int frequency)
waits the corresponding time from hz to ms.
void wait_ms (int millis)
Waits a number of milliseconds.
uint32_t wait_elapsed (uint32_t time)
Counts the time that has passed since the time received.
void wait_ChronoUs (uint32_t waitUs)
Waits a number of microseconds.
Detailed Description
Function Documentation
init_wait()
void init_wait ()
Initialises the wait API for 1 ms resolution.
Note
This function must be called prior to any other WAIT functions.
Definition at line 11 of file wait.c.
References CCLK_FREQ, MICROSECONDS_DIVISION, MILLISECONDS_DIVISION, MR0I, MR0S, RESET_STOPWATCH, TIMER0_CLK, and TIMER_MODE.
Referenced by init_peripherals().
wait_ChronoUs()
void wait_ChronoUs (uint32_t waitUs)
Waits a number of microseconds.
Parameters
waitUs wait a certain number of microseconds.
Note
blocking function
Definition at line 35 of file wait.c.
References MR0_INTERRUPT, and RESET_STOPWATCH.
wait_elapsed()
uint32_t wait_elapsed (uint32_t time)
Counts the time that has passed since the time received.
Parameters
time start time.
Returns
millis: the time that has passed or the current time if input parameter = 0.
Note
not blocking function
Definition at line 30 of file wait.c.
wait_hz()
void wait_hz (int frequency)
waits the corresponding time from hz to ms.
Parameters
frequency the whole number of hertz to wait.
Note
created for applications that needs a certain frequency. Blocking function
Definition at line 20 of file wait.c.
References wait_ms().
wait_ms()
void wait_ms (int millis)
Waits a number of milliseconds.
Parameters
millis the whole number of milliseconds to wait.
Note
blocking function
Definition at line 25 of file wait.c.
Referenced by init_LCDText(), and wait_hz().