Embedded Systems Library: UI Public Functions
UI Public Functions
UI
Functions
void init_ui (void)
Initializes UI control.
Detailed Description
Function Documentation
init_ui()
void init_ui (void)
Initializes UI control.
Returns
Nothing
Note
This function must be called first to interact with the hardware.
Definition at line 11 of file ui.c.
References init_BUTTON(), init_LCDText(), and init_led().
Referenced by init_peripherals().