Embedded Systems Library: LCD Public Functions
LCD Public Functions
lcd
This package provides the public functions of the LCD Display.
Functions
void init_LCDText (void)
LCD instruction initialization function to be able to send and control the LCD using 4 bits.
void LCDText_WriteChar (char ch)
Writes the given character on the LCD in the current cursor position.
void LCDText_WriteString (char *str)
Writes the given string on the LCD in the current cursor position.
void LCDText_Locate (int row, int column)
Put the cursor in the given position of the lcd.
void LCDText_Clear (void)
Clear the LCD Display.
void LCDText_Printf (char *fmt,...)
Writes the given string on the LCD in the current cursor position using a certain format.
void LCDText_PrintBinary (int bin)
void LCDText_Cursor (int state)
Detailed Description
This package provides the public functions of the LCD Display.
Function Documentation
init_LCDText()
void init_LCDText (void)
LCD instruction initialization function to be able to send and control the LCD using 4 bits.
Note
Call this function only at the beginning of the program and only once
Definition at line 25 of file lcd.c.
References LCD_DB4, LCD_DB5, LCD_DB6, LCD_DB7, LCD_ENABLE, LCD_RS, PINCFG_DB4, PINCFG_DB5, PINCFG_DB6, PINCFG_DB7, PINCFG_ENABLE, PINCFG_RS, and wait_ms().
Referenced by init_ui().
LCDText_Clear()
void LCDText_Clear (void)
Clear the LCD Display.
Note
The cursor goes back to the initial position, first line (0) and first column (0).
Definition at line 82 of file lcd.c.
Referenced by LCDText_PrintBinary().
LCDText_Cursor()
void LCDText_Cursor (int state)
Definition at line 75 of file lcd.c.
LCDText_Locate()
void LCDText_Locate (int row, int column)
Put the cursor in the given position of the lcd.
Parameters
row put the cursor at the first (0) or the second line(1).
column put the cursor at the given column (0-15).
Definition at line 69 of file lcd.c.
LCDText_PrintBinary()
void LCDText_PrintBinary (int bin)
Definition at line 99 of file lcd.c.
References LCDText_Clear(), LCDText_WriteString(), and MAX_CHAR.
LCDText_Printf()
void LCDText_Printf (char * fmt, ...)
Writes the given string on the LCD in the current cursor position using a certain format.
Parameters
fmt String to write.
Note
identical to the C printf library.
Definition at line 89 of file lcd.c.
References MAX_CHAR.
LCDText_WriteChar()
void LCDText_WriteChar (char ch)
Writes the given character on the LCD in the current cursor position.
Parameters
ch character to write.
Definition at line 49 of file lcd.c.
References col, and row.
Referenced by LCDText_WriteString().
LCDText_WriteString()
void LCDText_WriteString (char * str)
Writes the given string on the LCD in the current cursor position.
Parameters
str string to write.
Note
this function can change between lines if the string is to large
Definition at line 64 of file lcd.c.
References LCDText_WriteChar().
Referenced by LCDText_PrintBinary().