Embedded Systems Library: LED Public Functions
LED Public Functions
LED
Functions
void init_led ()
Initializes the LED API.
void turn_on_led ()
Turn LED on.
void turn_off_led ()
Turn LED off.
int led_get_state ()
Get LED state.
Detailed Description
Function Documentation
init_led()
void init_led ()
Initializes the LED API.
Returns
Nothing
Note
This function must be called prior to any other LED functions. The LED will started in the value passed in the parameter.
Definition at line 12 of file led.c.
References LED_PIN, and turn_off_led().
Referenced by init_ui().
led_get_state()
int led_get_state ()
Get LED state.
Returns
status of LED. The 0 indicate led is off and 1 LED is on.
Definition at line 27 of file led.c.
turn_off_led()
void turn_off_led ()
Turn LED off.
Returns
Nothing
Definition at line 22 of file led.c.
References LED_PIN.
Referenced by init_led().
turn_on_led()
void turn_on_led ()
Turn LED on.
Returns
Nothing
Definition at line 17 of file led.c.
References LED_PIN.