Embedded Systems Library: D:/Isel/19-20/Inverno/SE1/SE1920/inc/spi.h File Reference
spi.h File Reference
#include "LPC17xx.h"
Macros
#define SPI_FUNCTION 3
#define PINSEL_SCK_BIT_POS 30
#define PINSEL_MISO_BIT_POS 2
#define PINSEL_MOSI_BIT_POS 4
#define PCLK_SPI_BIT_POSITION 16
#define PCLK_CCLK_FUNCTION_L 2
#define BIT_ENABLE_BIT_POSITION 2
#define BITS_MODE 1
#define BITS_BIT_POSITION 8
#define BITS_MASK 0xF
#define MASTER_MODE_BIT_POSITION 5
#define MASTER_MODE 1
#define LSBF_BIT_POSITION 6
#define MSB_MODE_L 1
#define CPHA_CPOL_BIT_POSITION 3
#define CPHA_CPOL_BIT_MASK 0x3
#define CUSTOM_CONFIG_TRANSFER 0
#define DEFAULT_FREQUENCY 1
#define DEFAULT_DATABIT DEFAULT_FREQUENCY<<1
#define DEFAULT_MODE DEFAULT_FREQUENCY<<2
#define ABRT 1
#define MODF 2
#define ROVR 4
#define WCOL 8
#define SPIF 16
Enumerations
enum CPHA_CPOL_VALUES { CPHA_CPOL_LL =0, CPHA_CPOL_HL, CPHA_CPOL_LH, CPHA_CPOL_HH }
enum BITS {
EIGHT_BITS =8, NINE_BITS, TEN_BITS, ELEVEN_BITS,
TWELVE_BITS, THIRTEEN_BITS, FOURTEEN_BITS, FIFTEEN_BITS,
SIXTEEN_BITS =0
}
Functions
void init_spi (void)
int SPI_ConfigTransfer (int frequency, int bitData, int mode)
int SPI_Transfer (unsigned short *txBuffer, unsigned short *rxBuffer, int length)
Macro Definition Documentation
ABRT
#define ABRT 1
Definition at line 62 of file spi.h.
BIT_ENABLE_BIT_POSITION
#define BIT_ENABLE_BIT_POSITION 2
Definition at line 22 of file spi.h.
BITS_BIT_POSITION
#define BITS_BIT_POSITION 8
Definition at line 25 of file spi.h.
BITS_MASK
#define BITS_MASK 0xF
Definition at line 26 of file spi.h.
BITS_MODE
#define BITS_MODE 1
Definition at line 23 of file spi.h.
CPHA_CPOL_BIT_MASK
#define CPHA_CPOL_BIT_MASK 0x3
Definition at line 35 of file spi.h.
CPHA_CPOL_BIT_POSITION
#define CPHA_CPOL_BIT_POSITION 3
Definition at line 34 of file spi.h.
CUSTOM_CONFIG_TRANSFER
#define CUSTOM_CONFIG_TRANSFER 0
Definition at line 45 of file spi.h.
DEFAULT_DATABIT
#define DEFAULT_DATABIT DEFAULT_FREQUENCY<<1
Definition at line 47 of file spi.h.
DEFAULT_FREQUENCY
#define DEFAULT_FREQUENCY 1
Definition at line 46 of file spi.h.
DEFAULT_MODE
#define DEFAULT_MODE DEFAULT_FREQUENCY<<2
Definition at line 48 of file spi.h.
LSBF_BIT_POSITION
#define LSBF_BIT_POSITION 6
Definition at line 31 of file spi.h.
MASTER_MODE
#define MASTER_MODE 1
Definition at line 29 of file spi.h.
MASTER_MODE_BIT_POSITION
#define MASTER_MODE_BIT_POSITION 5
Definition at line 28 of file spi.h.
MODF
#define MODF 2
Definition at line 63 of file spi.h.
MSB_MODE_L
#define MSB_MODE_L 1
Definition at line 32 of file spi.h.
PCLK_CCLK_FUNCTION_L
#define PCLK_CCLK_FUNCTION_L 2
Definition at line 20 of file spi.h.
PCLK_SPI_BIT_POSITION
#define PCLK_SPI_BIT_POSITION 16
Definition at line 19 of file spi.h.
PINSEL_MISO_BIT_POS
#define PINSEL_MISO_BIT_POS 2
Definition at line 16 of file spi.h.
PINSEL_MOSI_BIT_POS
#define PINSEL_MOSI_BIT_POS 4
Definition at line 17 of file spi.h.
PINSEL_SCK_BIT_POS
#define PINSEL_SCK_BIT_POS 30
Definition at line 15 of file spi.h.
ROVR
#define ROVR 4
Definition at line 64 of file spi.h.
SPI_FUNCTION
#define SPI_FUNCTION 3
Definition at line 13 of file spi.h.
SPIF
#define SPIF 16
Definition at line 66 of file spi.h.
WCOL
#define WCOL 8
Definition at line 65 of file spi.h.
Enumeration Type Documentation
BITS
enum BITS
Enumerator
EIGHT_BITS
NINE_BITS
TEN_BITS
ELEVEN_BITS
TWELVE_BITS
THIRTEEN_BITS
FOURTEEN_BITS
FIFTEEN_BITS
SIXTEEN_BITS
Definition at line 50 of file spi.h.
CPHA_CPOL_VALUES
enum CPHA_CPOL_VALUES
Enumerator
CPHA_CPOL_LL
CPHA_CPOL_HL
CPHA_CPOL_LH
CPHA_CPOL_HH
Definition at line 37 of file spi.h.
Function Documentation
init_spi()
void init_spi (void)
Definition at line 11 of file spi.c.
References BIT_ENABLE_BIT_POSITION, BITS_MODE, LSBF_BIT_POSITION, MASTER_MODE, MASTER_MODE_BIT_POSITION, MSB_MODE_L, PCLK_CCLK_FUNCTION_L, PCLK_SPI_BIT_POSITION, PINSEL_MISO_BIT_POS, PINSEL_MOSI_BIT_POS, PINSEL_SCK_BIT_POS, and SPI_FUNCTION.
Referenced by init_peripherals().
SPI_ConfigTransfer()
int SPI_ConfigTransfer (int frequency, int bitData, int mode)
Definition at line 20 of file spi.c.
Referenced by get_chip_ID(), and measure().
SPI_Transfer()
int SPI_Transfer (unsigned short * txBuffer, unsigned short * rxBuffer, int length)
Definition at line 46 of file spi.c.
References MODF, SPIF, and WCOL.